language: php

php:
  - 7.3

addons:
  chrome: 
  - 73

install:
  - cp .env.testing .env
  - sudo apt-get update
  - sudo apt-get install chromium-browser
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  
before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - php artisan dusk
