language: php

php:
  - 7.3

addons:
  apt:
    packages:
      - chromium-chromedriver
      
install:
- sudo apt-get install php-xml
- sudo apt-get install php-curl
- sudo apt-get install php-zip
- composer install
- php artisan key:generate

before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  - composer update
script:
  - php artisan dusk
