php:
  - 7.3

addons:
  chrome:stable

install:
  - composer upadate
  - php -v
  - cp .env.testing .env
  - sudo apt-get install google-chrome-stable
  - sudo apt-get update
  - php artisan key:generate
  - php artisan dusk:install

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - php artisan dusk
