sudo: required
language: php

php:
  - 7.3

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  - cp .env.testing .env
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  
  cache:
  directories: node_modules
branches:
  only: master
  
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@^3
  - sleep 3

script:
  - php artisan dusk
