php:
  - 7.3

addons:
  chrome:stable

install:
  - cp .env.testing .env
  - sudo apt-get install google-chrome-stable
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - sudo apt-get update
  - php artisan key:generate

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - php artisan dusk
