language: php

php:
  - 7.3

addons:
  apt:
    packages:
      - chromium-chromedriver
      
install:
- composer install
- php artisan key:generate

before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  - composer update
  - php artisan serve &
script:
  - php artisan dusk
