language: php

php:
  - 7.3

addons:
  chrome:2.44

install:
  - cp .env.testing .env
  - sudo apt-get update
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  
before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - php artisan dusk
