version: 2
jobs:
  build:
    docker:
      -
        image: 'circleci/php:latest'
    steps:
      - checkout
      -
        run: 'echo "A first hello"'
      -
        run: 'sudo apt-get install -y libsqlite3-dev'
      -
        run: 'cp .env.testing .env'
      -
        run: 'composer -v'
      -
        run: 'composer install'
      -
        run: 'composer update'
      -
        run: vendor/bin/phpunit
      -
        run:
          name: 'Start Chrome Driver'
          command: bash ./vendor/laravel/dusk/bin/chromedriver-linux
          background: true
      -
        run:
          name: 'Run Laravel Server'
          command: 'php artisan serve'
          background: true
      -
        run:
          name: 'Run Laravel Dusk Tests'
          command: 'php artisan dusk'
