version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "A first hello"
      - run:
            command: ./vendor/laravel/dusk/bin/chromedriver-linux
            background: true

            - run:
                command: php artisan serve
                background: true

            - run:
                command: php artisan dusk
